### ISSUE TITLE
Parse Field.Value not possible with vcard 2.1 format parameters

### ISSUE THREAD

**Issue by gdchamal** [emersion/go-vcard#14]
When trying to test processing a vcf file exported using thunderbird, we encounter empty value for some fields, like email.

The vcard format is 2.1 and it appear that parameters are not encoded as key=value tuples as in format 3.0 and 4.0 they are. This make parseParam function of decoder.go parsing the Field.Value as a parameter value.

Example of format not parsed correctly :

```
begin:vcard
fn:someone
email;internet:someone@somewhere.tld
version:2.1
end:vcard
```

Using this temporary solution I get back Field.Value filled correctly , but bypass completly any parameters:

https://gist.github.com/gdchamal/43c58f9d581cee05c40706692f852373

Yes I know vcard2.1 format should not exist anymore ;)

What do you think ?

**Comment by emersion** [comment]
For reference, wiki page about differences between V2, V3 and V4: https://github.com/mangstadt/ez-vcard/wiki/Version-differences

I suspect we might want to parse raw lines, get the version, and then parse each line depending on the version.

**Comment by gdchamal** [comment]
I think that the best approach, but not the simplest to parse fields depending on the VERSION value.

So you're not reluctant to support vcard 2.1 format ;)

I close this issue and will try to come back with a pull request for such version parsing if you're OK.

**Comment by emersion** [comment]
>So you're not reluctant to support vcard 2.1 format ;)

Well, it's a little bit annoying, but if the code parsing v2 is clearly guarded behind version checks I suppose it will be fine :P
