### ISSUE TITLE
support change of Name and Address object fields

### ISSUE THREAD

**Issue by AlmogBaku** [emersion/go-vcard#16]
right now, changing the field value won't reflect the marshaled data

**Comment by emersion** [comment]
Works for me. You'll need to provide more details.

**Comment by AlmogBaku** [comment]
how can you change FirstName from a card in a way that you'll be able to re-encode the card?

See example here
https://play.golang.org/p/krws1_iJiWy

since `Name.field()` is private it's complicated to change the value without rebuilding the entry

**Comment by AlmogBaku** [comment]
the solution is quite simple, expose `field()` function and rename it... something like `url.URL{}.Query().Encode()` does (same problem)

**Comment by emersion** [comment]
We just need to add `SetName`. We already have `AddName`.

**Comment by AlmogBaku** [comment]
Anyhow, it doesn't help you unless you expose the encoding function...

**Comment by emersion** [comment]
No, I don't want to expose this private method.

**Comment by AlmogBaku** [comment]
why?

**Comment by AlmogBaku** [comment]
@emersion can you elaborate on why not just changing the name of the method to `Encode()`? this will allow updating existing names easily...
