### ISSUE TITLE
Reading telephone number

### ISSUE THREAD

**Issue by hasanAjsf** [emersion/go-vcard#23]
I noticed telephone number is defined as `TEL` https://github.com/emersion/go-vcard/blob/dd3110a24ec26a6b9f8a45da21cc0f2ca2ce8c67/card.go#L53 
And can be read as:
```go
log.Println(card.PreferredValue(vcard.FieldTelephone))
```

But in my vcard, telephone number is defined as:
```
Fitem1.TEL;waid=966000000000
```

How can I read it?

**Comment by emersion** [comment]
GitHub issues aren't for questions, sorry.
