### ISSUE TITLE
GetAllFields

### ISSUE THREAD

**Issue by InDaPond** [emersion/go-vcard#9]
I would love to access all Fields, so far you only can Get one(the preferred) value by calling Get.
You have access to all the Values, but that might not be sufficient: In my case, I want to have the details on all existing phone Numbers, so whether that phoneNumber is for Work, Home, Cell, etc.

So my simple suggestion:
```go
// GetAllFields returns all fields of the card for the given property. If there is    
// no such field, it returns nil.  
func (c Card) GetAllFields(k string) []*Field {  
	fields := c[k]  
	if len(fields) == 0 {  
		return nil  
	}  
	return fields  
}
```

and on that you can extract all necessary information.
Or is there a better way to extract all phone Numbers with the details on them?

**Comment by InDaPond** [comment]
okay im too stupid to format the code properly, how does a newline work in there?

**Comment by emersion** [comment]
Hi,

To get all fields you can just use regular map access:

```go
var card vcard.Card // Let's assume `card` is a vcard
tel := card[vcard.FieldTelephone]
emails, hasEmails := card[vcard.FieldEmail]
```

**Comment by InDaPond** [comment]
Thank you for the fast reply - this is indeed what I was looking for, therefore my issue makes no sense - CLOSED :)

**Comment by emersion** [comment]
It seems like the original data contains this +1 - vcard doesn't care about this, it just parses the field and returns its value. Read the original vcard file to check this.

Side note, don't use regexp when you have a good stdlib with things like `strings.TrimPrefix`.

**Comment by InDaPond** [comment]
Thanks, within all the contacts I took one as a sample which seemed fitting - but you are right again, it's a bug there. Thanks and hopefully finally Closed ;)
